Parameters:
  AccessControl:
    Type: String
    Default: PublicRead
    Description: Access Control value
  BucketName:
    Type: String
    Default: my-bucket
    Description: Logical Bucket Name
Outputs:
  Arn:
    Description: The Bucket Arn
    Value: !GetAtt 
      - MyBucket
      - Arn
  DomainName:
    Description: The Bucket Domain Name
    Value: !GetAtt 
      - MyBucket
      - DomainName
Description: Creates an S3 Bucket1692511718z6o1yg
Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  
